# W7.3 — P2 is FALSIFIED. Written before the campaign finished draining.

Written 2026-08-24, with 20 of 28 W7 cells complete. The A0 2×2 — the four cells
P2 is evaluated on — is complete at n=3 seeds each. P1, P4 and P5 are still open
and are not decided here.

**This memo is deliberately written while the campaign is still running.** P2 is
the first pre-registered falsifier to become evaluable, and it fails. Writing
the failure now, before the A1 cells that carry the campaign's positive case have
all landed, is the strongest evidence available that the reporting is not
selective: at the time of writing I do not know what P1 or P5 will say, and this
memo cannot have been shaped by them.

Per F11's fifth fix, `experiments/asplos/` was listed for W7 before writing.
`W7_PREREGISTRATION_2026-08-23.md` (§3, P2), `W7.1_KNOB_B_2026-08-24.md` (the
knob-B memo and its launch addendum) and `W7.2_A1_SIZING_2026-08-24.md` all bear
on this cell and are all read and cited below. **`W7.1`'s addendum already
contains a written prediction of this outcome**, and §4 of that addendum is
quoted here rather than paraphrased, because it is the reason this result is
reportable rather than embarrassing.

## 1. The prediction, verbatim

`W7_PREREGISTRATION_2026-08-23.md:128-130`:

> **P2 (O1 isolated, A0/B1).** Lines in flight rise from ~1.3 to **≥6**, and
> achieved fused bandwidth from 0.52 to **≥2.0 GB/s**. *Falsified below 3 lines*
> — the batching did not take, and the cell says nothing.

## 2. The arms

Every figure below is at the **A0** hierarchy point with **k = 16** batching,
and the two arms differ in exactly one flag. From the cells' own command lines:

    se.py --ruby --topology=Pt2Pt --chi-config=CHI_config_8592.py
      --num-l3caches=1 --num-dirs=1 --cpu-type=O3CPU --num-cpus=2
      --cpu-clock=1.9GHz --l1d_size=48KiB --l1d_assoc=12 --l1i_size=32KiB
      --l1i_assoc=8 --l2_size=2MiB --l2_assoc=16 --l3_size=5MiB --l3_assoc=20
      --mem-type=SimpleMemory --dram-latency=98ns --cxl-latency=203ns
      -c cxl_join_bench_w7.gem5
      --options '--mode morsel --policy {wb|stream} --fact-bytes 16777216
                 --hot-bytes 4194304 --reps 3 --warmups 1
                 --probe-batch {0|16} --json'

`--probe-batch 0` is B0, `--probe-batch 16` is B1. Nothing else differs. A0's
LLC is 5 MiB / 20-way = 4,096 sets exactly, so **[F9.4] does not apply to any
number in this memo** — checked against the set count, not assumed.

Correctness gate (F12: `--check` is inert in `--mode morsel`, so cross-arm
equality of `matches_last_rep` *is* the gate): all completed cells report
**521,979** matches. Invariant. The arms are comparable.

## 3. The result

A0, mean of 3 seeds per cell, bench-reported `stream_bandwidth_gbps` over the
timed region (not `simSeconds`-derived — see `w7_analyze.py`'s header):

| A0 cell | cyc/access | sd | fused GB/s | lines in flight | LLC hit % | DRAM rd MB | CXL rd MB | HNF fills |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| B0 (serial) WB | 69.101 | 0.061 | 0.440 | 1.40 | 53.69 | 12.16 | 66.76 | 1,341,405 |
| B0 (serial) H2 | 68.732 | 0.110 | 0.442 | 1.40 | 54.02 | 10.07 | 61.53 | 542,118 |
| **B1 (k=16) WB** | 55.191 | 0.018 | 0.551 | 1.75 | 53.79 | 12.99 | 66.88 | 1,359,160 |
| **B1 (k=16) H2** | **54.510** | 0.010 | **0.558** | **1.77** | 54.51 | 10.06 | 61.54 | 546,397 |

**P2 as registered: FALSIFIED.**

* Lines in flight at A0/B1 H2: **1.77**, against a target of ≥6 and an explicit
  falsification floor of **<3**. Below the floor by a factor of 1.7; below the
  target by a factor of 3.4.
* Fused bandwidth at A0/B1 H2: **0.558 GB/s**, against ≥2.0 GB/s. Short by 3.6×.

Seed-to-seed spread is negligible (sd 0.010–0.110 cyc/access on means near 55–69,
i.e. ≤0.16%), so this is not a variance question. Nothing about the falsification
is marginal.

## 4. The registered *explanation* of falsification does not hold, and this is
##    the substantive finding

The pre-registration attaches one reading to a sub-3-lines result: *"the batching
did not take, and the cell says nothing."* The first clause is **false**, and it
is falsified by the same four cells.

Batching took, cleanly and reproducibly:

* **cyc/access 68.732 → 54.510 under H2, a 20.7% improvement**; 69.101 → 55.191
  under WB, 20.1%. Both at ≥100× the seed spread.
* **Fused bandwidth +26.2% under H2** (0.442 → 0.558 GB/s), +25.2% under WB.
* **Traffic is unchanged**: CXL reads 61.53 → 61.54 MB under H2 (+0.02%), DRAM
  reads 10.07 → 10.06 MB, LLC hit rate 54.02 → 54.51%.

Improved time at constant fetched volume is the signature of a knob that
rescheduled memory accesses without changing which ones happen — which is
exactly and only what knob B was built to do. The transformation is not inert,
is not mis-plumbed, and is not policy-dependent (20.7% under H2 vs 20.1% under
WB: batching and admission are orthogonal here, which is itself a clean result).

So the correct verdict is a third one the pre-registration did not enumerate:

> **Batching took, and the MLP this kernel can express at this operating point
> is ~1.8 lines, not ≥6.** The registered threshold was not missed because the
> knob failed; it was missed because the kernel's ceiling is far below where the
> threshold was set.

Per §6.6 this is recorded as a shortfall in the *prediction*, not as a reason to
retune. `W7.1`'s addendum pre-committed to exactly this and forbade the escape
route in advance:

> If P2 falsifies at A0/B1 that is a real pre-registered outcome and it is
> reported as one — "batching raises MLP by 28% and 28% is not enough" is an
> answer about whether this kernel can express an admission benefit at all, and
> it is the answer the 2×2 was built to be able to give. **It is not a reason to
> retune k after the fact.**

`k` has not been retuned and will not be.

## 5. The prediction was already visible before the campaign, and it was accurate

`W7.1`'s addendum reports the A0 gem5 smoke at `--probe-batch 16` holding
**1.72** lines in flight, and states plainly that this is "not encouraging for
P2." The campaign's A0/B1 H2 cell measures **1.77**. The pre-campaign smoke
predicted the falsified quantity to within 3%.

Two consequences. First, the campaign did not discover this — the smoke did, and
the smoke was written up honestly at the time, including the unfavourable
reading. Second, the ~20 host-hours the A0 column cost bought confirmation at
n=3 of something a 0.63-hour smoke had already indicated, which is a sizing
lesson for the next campaign rather than a defence of this one.

## 6. Why the target was not unreasonable — the ceiling is measured, on this machine

The obvious objection to a 3.4× shortfall is that ≥6 lines was never reachable
here. It was. The A0 stream-smoke references, same geometry, same simulator,
same binary, `--mode stream-smoke`:

| A0 reference | fused GB/s | lines in flight | CXL passes over the fact array |
|---|---:|---:|---:|
| A0_SMOKE_wb | 3.960 | 12.56 | 5.03 |
| A0_SMOKE_stream | 4.609 | **14.62** | 3.89 |

Both are sound streaming references — at 3.89 and 5.03 passes the fact array is
genuinely re-fetched from CXL and is not LLC-resident. (The two *A1* smokes are
not references and are excluded: at 1.00 pass each, their 16 MiB fact array fits
A1's 20 MiB effective LLC and their 9.27 GB/s is an on-chip bandwidth. This is
already recorded in `W7.2`.)

So the machine sustains **14.6 lines in flight** when it does nothing but stream.
The registered ≥6 was 41% of that demonstrated ceiling — a conservative target,
not an optimistic one. The fused join, with k=16 batching engaged and working,
reaches **12% of it**.

The gap is therefore a property of **the fused kernel**, not of the simulated
memory system. Whatever limits it, it is not the CXL link, not the TBE budget,
and not the 203 ns latency — those are common to the smoke, which is 8× better.
A mechanism (the probe's hash → index → load → compare dependence, which
batching parallelizes across lanes but does not shorten) is the natural
candidate, but **it is not measured here and is offered as a hypothesis only**.

## 7. A limitation of the registered metric, stated — and explicitly not used to
##    reverse the verdict

"Lines in flight" is Little's law applied to the bench-reported bandwidth at
203 ns: `lines = GB/s × 1e9 × 203e-9 / 64 = GB/s × 3.1719`. It is therefore a
*monotone rescaling of the bandwidth figure* and carries no information the
bandwidth column does not. Two things follow, both of which cut against my own
report and are recorded for that reason:

1. **P2 is one test, not two.** "≥6 lines" is "≥1.892 GB/s"; the separate
   "≥2.0 GB/s" half is "≥6.34 lines". The two halves are the same threshold to
   within 6%, and the falsification floor of "<3 lines" is "<0.946 GB/s". That
   both halves fail is **not** independent corroboration and must not be
   presented as such.
2. There is **no MSHR-occupancy stat in this build**, so no direct measurement
   of outstanding lines exists. `lqAvgOccupancy` is a load-queue ratio, not
   lines outstanding; the pre-registration names it and forbids substituting it.

Both limitations were written down *before* the data existed. Per §6.6 and the
row-35 extension of §5.1 from arms to metrics, a metric registered in advance is
not swapped out after seeing the result it produced. The verdict stands on the
metric as registered. Anyone who prefers a different MLP metric may argue the
point, but they must argue it against the bandwidth column, which is the same
test in different units and fails by 3.6×.

## 8. What this costs, and what it does not

**Costs.** The pre-registration's §4 lays out a strong-negative story that
requires "P3 fails at A1/B1 with P1 and P2 both confirmed." **That story is no
longer available**, because P2 is not confirmed. Any W7 negative must now be
reported in the weaker form: the convergence cell was tested at an operating
point where one of its two knobs demonstrably did not reach the strength it was
designed to reach.

**Does not cost.** The A0/B1 cell is not junk, notwithstanding "the cell says
nothing." At that cell H2 removes **59.8% of HNF fills** (1,359,160 → 546,397)
and **22.6% of DRAM reads** (12.99 → 10.06 MB) while moving cyc/access by
**1.23%** (55.191 → 54.510). That is a large, unambiguous change in allocation
behaviour producing a ~1% change in time — which is a direct, quantitative
statement of the L3 problem this project has been circling, measured rather than
argued. It is reported as an observation about A0/B1, not as a P2 outcome.

§5.2 check applied before believing that ~1% null: A0's **private L2 is 2 MiB**
per core and the hot table is **4 MiB**, so the victim set does not fit the
private L2 and the null is not an L2-residency artifact. Verified against the
instantiated `--l2_size`, not the LLC.

## 9. Status of the other falsifiers — open, and not decided by this memo

* **P1** (A1/B0): incomplete. Those cells have not landed.
* **P3** (A1/B1): the cell completed at n=3 while this memo was being written,
  and computes at **+0.63%** cyc/access WB→H2 (66.757 → 66.338, sd 0.015 both
  arms) against "≥5, falsified <2". It is **not** adjudicated here — it gets its
  own memo — but `W7.2`'s reading rule, registered before the data, already
  governs it: P1 and P3 are evaluated at A1, whose realized geometry is 20 MiB /
  40× / 40% rather than the pre-registered 32 MiB / 64× / 25%, so **a falsified
  P1 or P3 may not be reported as falsifying the registered prediction.**
* **P4**: not computable in SE mode at all; needs a resctrl arm.
* **P5**: incomplete.

**The same rule does not protect P2.** `W7.2` says so explicitly: *"P2 is
unaffected: it is evaluated at A0/B1 against the A0 reference, and A0's
reference is sound."* A0 is not mis-sized, its smokes are genuine streaming
references at 3.89 and 5.03 passes, and F9.4 does not touch it. **P2's
falsification stands unprotected, and is the campaign's first hard negative.**
